### PR TITLE
Update Meeting-Reality.md

### PR DESCRIPTION
**Pull request by chrisatx**
Fix typo.
I may find additional typos. Not sure if I should do a PR for each as I go or in a batch...
Or if this small of a typo should be collected into an issue and not worry about PRs.

### CODE REVIEW

**Comment by robmoffat** [comment]
Perfect, thanks Chris.

**Comment by robmoffat** [comment]
I like to credit everyone who helped improve this.  What is your preference: refer to you as ChrisJ or do you want a full-name / no mention?

thanks

**Comment by chrisatx** [comment]
No mention is good - drive-by contributions :-) 
Great job and thanks for the readings/resources.

**Comment by robmoffat** [comment]
heh ok, an "anonymous donor"!
cheers

**Pull request merged**
