### PR TITLE
.htaccess file added and Images Proper Scaling

### PR DESCRIPTION
**Pull request by realabbas**
# For better browser leverage caching and Scaling of Images

 I ran a test on the website and found that there is not caching available for browser 

**Screenshots of Test Report**
 
image

image

This can be solved by adding a **.htaccess file for caching**. I have made the necessary changes and hence will increase the page speed of the website 

**Full Report:** https://gtmetrix.com/reports/riskfirst.org/cqr7GiEh

Also Scaled two images. It saves hell lot of a data now.

### CODE REVIEW

**Comment by realabbas** [comment]
> # For better browser leverage caching and Scaling of Images
> I ran a test on the website and found that there is not caching available for browser
> 
> **Screenshots of Test Report**
> 
> image
> 
> image
> 
> This can be solved by adding a **.htaccess file for caching**. I have made the necessary changes and hence will increase the page speed of the website
> 
> **Full Report:** https://gtmetrix.com/reports/riskfirst.org/cqr7GiEh
> 
> Also Scaled two images. It saves hell lot of a data now.

@robmoffat Any Update?

**Comment by robmoffat** [comment]
I've not seen this tool before - looks really good! Thanks for your work

**Comment by realabbas** [comment]
@robmoffat That's great. Thanks :blush:

**Comment by andreadellacorte** [comment]
Does .htaccess work with Github Pages? I just ran a gtmetrix report myself and caching is still unavailable

**Pull request merged**
